(module info (lib "infotab.ss" "setup")
  (define name "tqueue")
  (define blurb '("A queue-like data structure for topological sorting. "))
  (define version "1.0")
  (define primary-file "tqueue.ss")
  (define scribblings '(("manual.scrbl" ())))
  (define doc.txt "manual.txt")
  (define homepage "http://hashcollision.org/")
  (define can-be-loaded-with 'all)
  (define required-core-version "399")
  (define categories '(datastructures)))